### ISSUE TITLE
Create a README

### ISSUE THREAD

**Issue by qdrn** [massalabs/demoyard#2]
We should make something similar to what is done in massa-sc-examples.

**Comment by qdrn** [comment]
Can someone from the @massalabs/run team handle that ?

**Comment by 0xB19** [comment]
Sure !

**Comment by Elli610** [comment]
Hi @qdrn !

Can you give me more details about the purpose of this repo ?

**Comment by thomas-senechal** [comment]
> Can you give me more details about the purpose of this repo ?

This repository is what has been made during this Live Coding: https://www.youtube.com/live/gliOv6ICWRg

It's a trading bot that shows how to use Autonomous SCs and MassaWeb3. 
There are more explainations in the Live Coding.

**Comment by qdrn** [comment]
> Hi @qdrn !
> 
> Can you give me more details about the purpose of this repo ?

If you need more details you can have a quick chat with @AurelienFT. Unfortunately I haven't had time to watch it myself :(.
